import { Link } from 'react-router-dom';
import { Map, Mail, Phone, Instagram, Twitter, Linkedin, Github } from 'lucide-react';

const Footer = () => {
  return (
    <footer className="bg-slate-900 text-slate-300 py-12 px-6 mt-16 border-t font-sans">
      <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-10">

        <div className="space-y-4">
          <Link to="/" className="flex items-center gap-2 text-white group">
            <div className="bg-brand-500 p-2 rounded-lg group-hover:bg-brand-600 transition-colors">
              <Map size={24} />
            </div>
            <span className="text-2xl font-bold">Trippzy</span>
          </Link>
          <p className="text-sm leading-relaxed max-w-sm">
            Your AI-powered travel companion. Plan perfect trips with personalized itineraries generated by artificial intelligence. Make every journey unforgettable.
          </p>
          <div className="flex flex-row space-x-4 pt-2">
            <a href="https://www.linkedin.com/in/prashanth-goud-372485294/" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors"><Linkedin size={20} /></a>
            <a href="https://github.com/Prashanthgoud15" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors"><Github size={20} /></a>
            <a href="#" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors"><Instagram size={20} /></a>
            <a href="#" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors"><Twitter size={20} /></a>
          </div>
        </div>

        <div>
          <h3 className="text-white font-semibold text-lg mb-4">Quick Links</h3>
          <ul className="space-y-3 text-sm">
            <li><Link to="/" className="hover:text-brand-400 transition-colors">Home</Link></li>
            <li><Link to="/planner" className="hover:text-brand-400 transition-colors">Plan Trip</Link></li>
            <li><Link to="/trips" className="hover:text-brand-400 transition-colors">My Trips</Link></li>
            <li><Link to="/profile" className="hover:text-brand-400 transition-colors">Profile</Link></li>
          </ul>
        </div>

        <div>
          <h3 className="text-white font-semibold text-lg mb-4">Contact Us</h3>
          <ul className="space-y-4 text-sm">
            <li className="flex items-start gap-3">
              <Phone size={18} className="text-brand-500 mt-1" />
              <div>
                <span className="block text-white">Phone:</span>
                <a href="tel:+917842432439" className="hover:text-brand-400 transition-colors">+91 7842432439</a>
              </div>
            </li>
            <li className="flex items-start gap-3">
              <Mail size={18} className="text-brand-500 mt-1" />
              <div>
                <span className="block text-white">Email:</span>
                <a href="mailto:goudprashanth691@gmail.com" className="hover:text-brand-400 transition-colors">goudprashanth691@gmail.com</a>
              </div>
            </li>
          </ul>
          <div className="mt-8 flex flex-col gap-2 text-sm">
            <Link to="/" className="hover:text-brand-400 transition-colors">Privacy Policy</Link>
            <Link to="/" className="hover:text-brand-400 transition-colors">Terms of Service</Link>
          </div>
        </div>
      </div>

      <div className="max-w-6xl mx-auto mt-12 pt-8 border-t border-slate-800 text-center text-sm">
        <p>&copy; {new Date().getFullYear()} Trippzy. All rights reserved. Made for travelers.</p>
      </div>
    </footer>
  );
};

export default Footer;
